seeyon-unauthorized
chaitin/xray pull request #1009
Opened 2021-01-10 17:02 UTC by x1n9Qi8

## 本 poc 是检测什么漏洞的
由于致远OA旧版本某些接口存在未授权访问，以及部分函数存在过滤不足，攻击者通过构造恶意请求，可在无需登录的情况下上传恶意脚本文件，从而控制服务器。
## 测试环境
https://fofa.so/result?qbase64=YXBwPSLoh7Tov5xBOCI=
## 备注

2021-01-18 09:26 UTC, zema1 requested changes

2021-01-18 09:26 UTC, zema1 commented on pocs/seeyon-unauthorized.yml
> +      response.status == 200 && response.body.bcontains(bytes("MMOneProfile")) && response.body.bcontains(bytes("productTags")) && response.body.bcontains(bytes("serverIdentifier"))
这个加一个 json 的判断吧

2021-01-18 09:26 UTC, zema1 commented on pocs/seeyon-unauthorized.yml
> +name: poc-yaml-seeyon-unauthorized
名字要不加一个 ajax，类似 `poc-yaml-seeyon-ajax-unauthorized-access` 要不太泛化了

2021-01-19 01:26 UTC, x1n9Qi8 commented on pocs/seeyon-unauthorized.yml
> +name: poc-yaml-seeyon-unauthorized
已经修改了

2021-01-19 02:30 UTC, zema1 commented
感谢提交~ 给力师傅

2021-01-19 02:30 UTC, merged