frp-defaultpassword
chaitin/xray pull request #1020
Opened 2021-01-15 02:05 UTC by x7iaob

## 本 poc 是检测什么漏洞的
frp默认密码admin/admin
## 测试环境
私聊
## 备注

2021-01-18 07:07 UTC, zema1 commented
麻烦把这个poc 和另一个不需要密码的写在一块吧，默认密码也是一种未授权访问，作为未授权访问的 poc 比较合适

2021-01-18 07:23 UTC, x7iaob commented
> 麻烦把这个poc 和另一个不需要密码的写在一块吧，默认密码也是一种未授权访问，作为未授权访问的 poc 比较合适

已修改

2021-01-18 09:29 UTC, zema1 requested changes

2021-01-18 09:29 UTC, zema1 commented on pocs/frp-default-password.yml
> +name: poc-yaml-frp-default-password
名字 dashboard 未授权访问的吧

2021-01-19 01:35 UTC, x7iaob commented on pocs/frp-default-password.yml
> +name: poc-yaml-frp-default-password
ok了

2021-01-19 02:32 UTC, zema1 requested changes

2021-01-19 02:32 UTC, zema1 commented on pocs/frp-dashboard-unauth.yml
> +        response.status == 200 && response.body.bcontains(b"proxies")
这个 api 的 `content-type` 应该是 json 吧，加个 content-type 的判断吧，这样很容易误报的

2021-01-19 03:22 UTC, x7iaob commented on pocs/frp-dashboard-unauth.yml
> +        response.status == 200 && response.body.bcontains(b"proxies")
Content-Type: text/plain; charset=utf-8

已修改

2021-01-19 08:49 UTC, merged