Foosun-sqli
chaitin/xray pull request #1027
Opened 2021-01-18 09:30 UTC by x7iaob

## 本 poc 是检测什么漏洞的

## 测试环境

## 备注

2021-01-18 10:28 UTC, zema1 requested changes
补充点 details 信息吧。。

2021-01-18 10:54 UTC, x7iaob commented
> 补充点 details 信息吧。。

ok了

2021-01-19 02:45 UTC, zema1 requested changes

2021-01-19 02:45 UTC, zema1 commented on pocs/foosun-sqli.yml
> +name: poc-yaml-foosun-sqli
感觉叫 dotnetcms 更好一点吧，这个是官方的名称

2021-01-19 03:21 UTC, x7iaob commented on pocs/foosun-sqli.yml
> +name: poc-yaml-foosun-sqli
行的，这个命中率还可以，我测试过。

2021-01-19 08:46 UTC, merged

2021-01-19 08:47 UTC, zema1 commented
感谢大佬~