axis2-default-password
chaitin/xray pull request #1050
Opened 2021-01-26 09:23 UTC by flyinbedxyz

**请先认真阅读下列要求，如不符合会被直接关闭 PR**

- 确保当前 POC 与已有的 POC 没有重复，除了仓库 `pocs` 目录中的，还有内置的几个用 Go 写的 POC也不要重复：
  ```
  poc-go-php-cve-2019-11043-rce
  poc-go-seeyon-htmlofficeservlet-rce
  poc-go-tongda-lfi-upload-rce
  poc-go-tongda-arbitrary-auth
  poc-go-ecology-dbconfig-info-leak
  poc-go-tomcat-put
  poc-go-tomcat-cve-2020-1938
  ```
  
- 阅读规范和要求 
  - https://chaitin.github.io/xray/#/guide/contribute
  - https://chaitin.github.io/xray/#/guide/high_quality_poc

- 一个 pull request 只提交一个 poc

- 对于 0day / 1 day 等未大面积公开细节的漏洞请勿提交，可以私聊群管理员

 - 不接受没有测试环境的 poc，测试环境可以使用 [vulhub](https://github.com/vulhub/vulhub/) 或 [vulnapps](https://github.com/Medicean/VulApps)，也可以提供 fofa/zoomeye/shodan 等搜索关键字。 请勿直接填写公网上未修复的站点的地址，如果有特殊情况，请私聊群内管理解决。
 
- 如果你的 poc 被合并或者没有合并但是评论说需要发送奖励，请查看 https://chaitin.github.io/xray/#/guide/feedback 并添加最下面的微信，说明你的 poc 地址，方便发送奖励。

**我是分割线，在提交 poc 填写说明的时候，请务必阅读上方要求，然后删除本分割线和上方的内容，只保留下面自定义的部分即可，否则不予通过。**

----------

## 本 poc 是检测什么漏洞的
axis2 默认口令，可进一步拿权
## 测试环境
tomcat7 axis2
tomcat8 axis2
dockerhub angig/axis2
## 备注

2021-01-26 11:15 UTC, phith0n requested changes

2021-01-26 11:15 UTC, phith0n commented on pocs/axis2-default-password.yml
> +      response.status == 200 && response.body.bcontains(b"Upload Service")
这个特征不行，太常见了。

2021-01-26 15:45 UTC, flyinbedxyz commented on pocs/axis2-default-password.yml
> +      response.status == 200 && response.body.bcontains(b"Upload Service")
特征已修改为超链接a标签的正则匹配

2021-01-27 03:46 UTC, phith0n commented
需要fofa上的一些数据支撑，弱口令的占比数量如何。

2021-01-27 07:51 UTC, flyinbedxyz commented
> 需要fofa上的一些数据支撑，弱口令的占比数量如何。
这个之前给某省cert做渗透时遇到过一个，也成功拿权了，poc测试也是成功的。刚才在fofa上测试了一下，直接以title="Axis2 - Home"，找到的200多个都没跑出默认口令，可能被墙了一半。fofa上能查到的估计很少，不过没准就有遗漏的。

2021-03-18 06:08 UTC, closed without merging