Update nexus-default-password.yml
chaitin/xray pull request #1057
Opened 2021-02-04 06:41 UTC by harris2015

----------

## 本 poc 是检测什么漏洞的

nexus-default-password

## 测试环境

已私

## 备注

修改误报

2021-02-10 03:53 UTC, phith0n commented
是不是多提交了一个minio的POC？

2021-02-10 03:53 UTC, phith0n requested changes

2021-02-10 03:53 UTC, phith0n commented on pocs/minio-default-password.yml
> +  poc2:
这个地方为什么要使用poc groups？

2021-02-10 03:53 UTC, phith0n commented on pocs/nexus-default-password.yml
> +      response.status == 200 && response.content_type.contains("json") && response.body.bcontains(b"loggedIn")
这个规则感觉不是很严谨，会有误报。

2021-02-16 05:15 UTC, harris2015 commented on pocs/minio-default-password.yml
> +  poc2:
为了适应新旧版本

2021-02-16 05:16 UTC, harris2015 commented on pocs/nexus-default-password.yml
> +      response.status == 200 && response.content_type.contains("json") && response.body.bcontains(b"loggedIn")
误报率应该比之前低，，，

2021-03-02 09:33 UTC, phith0n commented
麻烦把PR里的minio-default-password.yml删掉吧

2021-03-03 00:25 UTC, harris2015 commented
> 麻烦把PR里的minio-default-password.yml删掉吧

done

2021-03-04 06:51 UTC, closed without merging

2021-03-04 06:51 UTC, harris2015 commented
open a new one for this ：https://github.com/chaitin/xray/pull/1114