kyan-network-monitoring-account-password-leakage
chaitin/xray pull request #1188
Opened 2021-04-16 03:36 UTC by B1anda0

## 本 poc 是检测什么漏洞的
Kyan 网络监控设备 账号密码泄露漏洞
## 测试环境
FOFA：  title="platform - Login"
## 备注
![image](https://user-images.githubusercontent.com/74232513/114967993-088bb500-9ea8-11eb-8a97-788a9661eca7.png)

2021-04-16 04:32 UTC, virusdefender requested changes

2021-04-16 04:32 UTC, virusdefender commented on kyan-network-monitoring-account-password-leakage.yml
> +      response.status == 200 && response.body.bcontains(b"UserName=") && response.body.bcontains(b"Password=")
这个容易误报吧，比如可能匹配到一些登录页面等，建议再匹配下页面上的 kyan 设备的一些特征

2021-04-18 12:11 UTC, B1anda0 commented on kyan-network-monitoring-account-password-leakage.yml
> +      response.status == 200 && response.body.bcontains(b"UserName=") && response.body.bcontains(b"Password=")
已做部分修改，在请求响应包中并无kyan的标识特征，故无法进行匹配。

2021-04-20 10:05 UTC, smile-jpg commented
多提交了一个文件吧

2021-04-21 02:03 UTC, B1anda0 commented
已删除多余文件

2021-04-23 10:45 UTC, smile-jpg commented
可以考虑匹配到账号密码之后，再发个登录请求，然后根据是否登录成功作为匹配标准

2021-04-25 09:50 UTC, B1anda0 commented
已修改，请审核

2021-04-27 07:47 UTC, smile-jpg commented on kyan-network-monitoring-account-password-leakage.yml
> +    body: user=admin&passwd={{pass}}
用户名一定是 admin 么？

2021-04-27 08:12 UTC, B1anda0 commented on kyan-network-monitoring-account-password-leakage.yml
> +    body: user=admin&passwd={{pass}}
目前测试存在漏洞资产用户名均为admin

2021-04-28 10:43 UTC, merged