thinkcmf-lfi  poc
chaitin/xray pull request #827
Opened 2020-08-12 08:25 UTC by jerry1995

**请先确保符合以下几点要求**

 - 阅读 poc 提交规范和要求 https://chaitin.github.io/xray/#/guide/contribute https://chaitin.github.io/xray/#/guide/high_quality_poc
 - 本 repo 中已经合并的和未合并的 pull request 中不含有相同的 poc，可以在网页端左上角搜索查看
 - 一个 pull request 尽量只提交一个 poc，否则可能审核和修改过程会互相影响
 - 对于 0day / 1 day 等未大面积公开细节的漏洞请勿提交，可以私聊群管理员
 - 下方的测试环境可以参考 [vulhub](https://github.com/vulhub/vulhub/) [vulnapps](https://github.com/Medicean/VulApps) 。请勿直接填写公网上未修复的站点的地址，如果有特殊情况，请私聊解决。不接受没有测试环境的 poc
 - 如果你的 poc 被合并或者没有合并但是评论说需要发送奖励，请查看 https://chaitin.github.io/xray/#/guide/feedback 并添加最下面的微信，说明你的 poc 地址，方便发送奖励。

**我是分割线，在提交 poc 填写说明的时候，请务必阅读上方要求，然后删除本分割线和上方的内容，只保留下面自定义的部分即可，否则不予通过。**

----------

## 本 poc 是检测什么漏洞的

## 测试环境

## 备注

2020-08-14 03:24 UTC, zema1 commented
CI 没过，麻烦再调整一下~

2020-08-24 09:53 UTC, zema1 requested changes

2020-08-24 09:53 UTC, zema1 commented on pocs/thinkcmf-lfi.yml
> +      response.status == 200 && response.body.bcontains(bytes(string(b"## README")))
特征有点弱了，如果 / 路径本身就存在 `## README` 就会误报

2020-08-25 02:56 UTC, jerry1995 commented
已更换特征

2020-08-27 03:08 UTC, zema1 requested changes

2020-08-27 03:08 UTC, zema1 commented on pocs/thinkcmf-lfi.yml
> +      response.status == 200 && response.body.bcontains(bytes(string(b"root")))
如果能包含一个框架本身的文件是最好的，这样写这个 poc 只能扫出 linux 下搭建的情况了。 之前的 README 不是不可以，只是很容易误报，如果能特征强一些或者换其他框架特征明显的文件比较好

2020-08-27 12:27 UTC, jerry1995 commented
这样是否好些？

2020-09-16 07:41 UTC, merged

2020-09-16 07:42 UTC, zema1 commented
不好意思久等了，感谢贡献，奖励措施参考：https://docs.xray.cool/#/guide/rewards

请添加 https://chaitin.github.io/xray/#/guide/feedback 页面最下方的微信，单个 POC 即可进入核心开发者群交流，还有不定期的奖励发送~