Create uediter-anyfile-upload-cnvd-2017-20077.yml
chaitin/xray pull request #878
Opened 2020-08-31 04:00 UTC by ppbibo

**请先认真阅读下列要求，如不符合会被直接关闭 PR**

- 确保当前 POC 与已有的 POC 没有重复，除了仓库 `pocs` 目录中的，还有内置的几个用 Go 写的 POC也不要重复：
  ```
  poc-go-php-cve-2019-11043-rce
  poc-go-seeyon-htmlofficeservlet-rce
  poc-go-tongda-lfi-upload-rce
  poc-go-ecology-dbconfig-info-leak
  poc-go-tomcat-put
  poc-go-tomcat-cve-2020-1938
  ```
  
- 阅读规范和要求 
  - https://chaitin.github.io/xray/#/guide/contribute
  - https://chaitin.github.io/xray/#/guide/high_quality_poc

- 一个 pull request 只提交一个 poc

- 对于 0day / 1 day 等未大面积公开细节的漏洞请勿提交，可以私聊群管理员

 - 不接受没有测试环境的 poc，测试环境可以使用 [vulhub](https://github.com/vulhub/vulhub/) 或 [vulnapps](https://github.com/Medicean/VulApps)，也可以提供 fofa/zoomeye/shodan 等搜索关键字。 请勿直接填写公网上未修复的站点的地址，如果有特殊情况，请私聊群内管理解决。
 
- 如果你的 poc 被合并或者没有合并但是评论说需要发送奖励，请查看 https://chaitin.github.io/xray/#/guide/feedback 并添加最下面的微信，说明你的 poc 地址，方便发送奖励。

**我是分割线，在提交 poc 填写说明的时候，请务必阅读上方要求，然后删除本分割线和上方的内容，只保留下面自定义的部分即可，否则不予通过。**

----------

## 本 poc 是检测什么漏洞的
UEditor .Net版本任意文件上传漏洞

## 测试环境
https://www.bingdou.net/code/332.html

## 备注
![image](https://user-images.githubusercontent.com/36287351/91681564-5eae2100-eb81-11ea-8063-bc9365013719.png)

2020-08-31 04:01 UTC, ppbibo commented
这个漏洞在项目上还是挺常见的。

2020-09-03 01:41 UTC, zema1 requested changes

2020-09-03 01:41 UTC, zema1 commented on pocs/uediter-anyfile-upload-cnvd-2017-20077.yml
> +      User-Agent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36'
`user-agent` 如果没有特殊用途，麻烦去掉

2020-09-03 01:41 UTC, zema1 commented on pocs/uediter-anyfile-upload-cnvd-2017-20077.yml
> +name: poc-yaml-uediter-anyfile-upload-cnvd-2017-20077
改成 `poc-yaml-uediter-cnvd-2017-20077-file-upload` 好一些

2020-09-03 01:42 UTC, ppbibo commented on pocs/uediter-anyfile-upload-cnvd-2017-20077.yml
> +name: poc-yaml-uediter-anyfile-upload-cnvd-2017-20077
好的

2020-09-03 01:42 UTC, zema1 commented
另外，可否映射个公网测试地址，我这没有 .net 环境，搭起来有些麻烦。 可以再交流群私聊我 @ koalr

2020-09-03 02:08 UTC, zema1 commented
不好意思久等了，感谢贡献，奖励措施参考：https://docs.xray.cool/#/guide/rewards

请添加 https://chaitin.github.io/xray/#/guide/feedback 页面最下方的微信，单个 POC 即可进入核心开发者群交流，还有不定期的奖励发送~

2020-09-03 02:08 UTC, merged