Create hikvision-cve-2017-7921.yml
chaitin/xray pull request #886
Opened 2020-09-04 08:44 UTC by whwlsfb

## 本 poc 是检测什么漏洞的

本Poc是用于检测海康威视摄像头Web管理界面的未授权访问漏洞
详见：https://packetstormsecurity.com/files/144097/Hikvision-IP-Camera-Access-Bypass.html

## 测试环境

摄像头大部分处于内网环境，暂无测试环境。
测试截图如下：
![hik.png](https://i.loli.net/2020/09/04/zFehBRw8VQgWuyx.png)

## 备注

以下产品和版本受到影响：
HikvisionDS-2CD2xx2F-ISeries5.2.0build140721版本至5.4.0build160530版本；
DS-2CD2xx0F-ISeries5.2.0build140721版本至5.4.0Build160401版本；
DS-2CD2xx2FWDSeries5.3.1build150410版本至5.4.4Build161125版本；
DS-2CD4x2xFWDSeries5.2.0build140721版本至5.4.0Build160414版本；
DS-2CD4xx5Series5.2.0build140721版本至5.4.0Build160421版本；
DS-2DFxSeries5.2.0build140805版本至5.4.5Build160928版本；
DS-2CD63xxSeries5.0.9build140305版本至5.3.5Build160106版本。

2020-09-16 08:12 UTC, zema1 requested changes

2020-09-16 08:12 UTC, zema1 commented on pocs/hikvision-cve-2017-7921.yml
> +      response.status == 200 && response.body.bcontains(b"<firmwareVersion>")
这个响应固定是 xml 的，麻烦加个 content_type 的判断吧

2020-09-16 09:22 UTC, whwlsfb commented on pocs/hikvision-cve-2017-7921.yml
> +      response.status == 200 && response.body.bcontains(b"<firmwareVersion>")
已添加判断

2020-09-17 08:14 UTC, zema1 commented
👍  不好意思久等了，感谢贡献，奖励措施参考：https://docs.xray.cool/#/guide/rewards

请添加 https://chaitin.github.io/xray/#/guide/feedback 页面最下方的微信，单个 POC 即可进入核心开发者群交流，还有不定期的奖励发送~

2020-09-17 08:14 UTC, merged