Create CDG-cve-2019-9632.yml
chaitin/xray pull request #901
Opened 2020-09-19 14:09 UTC by i-liberty

## 本 poc 是检测什么漏洞的
亿赛通电子文档安全管理系统任意文件下载漏洞
## 测试环境
https://classic.fofa.so/result?qbase64=Q0RHU2VydmVyMw%3D%3D
## 备注
detail:
  author: liberty
  links:
    - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9632exploit-db
![截图20200912](https://user-images.githubusercontent.com/18664862/93669156-7fa0cc80-fac4-11ea-926a-57a1eef4d7c0.png)

2020-09-19 14:59 UTC, i-liberty reviewed
### 本 poc 是检测什么漏洞的
Jeecg 信息泄露
### 测试环境
https://classic.fofa.so/result?q=title%3D%3D%22Jeecg+%E5%BF%AB%E9%80%9F%E5%BC%80%E5%8F%91%E5%B9%B3%E5%8F%B0%22&qbase64=dGl0bGU9PSJKZWVjZyDlv6vpgJ%2FlvIDlj5HlubPlj7Ai
### 备注
detail:
  author: liberty
  links:
    - https://blog.csdn.net/caiqiiqi/article/details/88672752
    - https://xz.aliyun.com/t/4405

2020-11-04 05:50 UTC, zema1 requested changes

2020-11-04 05:50 UTC, zema1 commented on pocs/cdg-cve-2019-9632.yml
> +      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
不要设置与该漏洞无关的 header，这个配置可以在配置文件全局指定。

2020-11-04 05:50 UTC, zema1 commented on pocs/jeecg-info-leak.yml
> +      response.status == 200 && response.body.bcontains(b"ResultCode") && response.body.bcontains(b"SESSIONID") && response.body.bcontains(b"ConcurrentMax") && response.body.bcontains(b"RequestTimeMi
这个响应如果是 json，判断下 content-type 比较好

2020-11-04 05:52 UTC, zema1 commented
感谢提交，我评论了几个小问题，麻烦对应的改一下，然后将这个三个 poc 分三个 PR 提交。

2020-11-04 05:52 UTC, closed without merging