Vmware
chaitin/xray pull request #909
Opened 2020-10-14 02:07 UTC by MrPointSun

##  本 poc 是检测什么漏洞的
Vmware Vcenter 任意文件读取
## 测试环境
app="vmware-VirtualCenter"
## 备注
提供了linux和windows两种poc，且是新漏洞，暂无CVE编号。

2020-10-14 02:51 UTC, virusdefender requested changes

2020-10-14 02:51 UTC, virusdefender commented on pocs/vmware-vcenterserveranyfile-read-linux.yml
> +    expression: |
windows 和 Linux 能不能都使用一个相对路径上的文件啊，这样可以统一来写，而且不会因为不在 c 盘等出现漏报

2020-10-14 02:51 UTC, virusdefender commented on pocs/vmware-vcenterserveranyfile-read-linux.yml
> +    - https://mp.weixin.qq.com/s?__biz=MzUzNTEyMTE0Mw==&mid=2247484201&idx=1&sn=d734aba7317a59f157e019b3084e15bf&chksm=fa8b1eb1cdfc97a7e667031aaec11fbcafb88aa181705f3e79b70fe0d329fc38ecdf1e4c7ec3&mps
使用原始来源吧，这个公众号的链接也太长了

2020-10-14 11:55 UTC, MrPointSun commented
已更改使用原始链接。
未找到相对路径，尝试搭建环境寻找，但要求配置过高，需要2个CPU+8G内存，搭不起来，如果大佬找到了相对路径可以直接更改- -

2020-10-14 12:05 UTC, MrPointSun commented
如果怕发生漏报的话，还有个思路是找 C:\WINDOWS\Win.ini ,大佬觉得哪种好一点？

2020-11-04 07:27 UTC, zema1 commented
我这边也没有本地搭过，尽量再找一下吧

2020-11-06 02:41 UTC, zema1 commented
这种不太好找的话 就保留两个吧 我下下个版本会更新一下 poc 的写法，把两个 poc 合成一个

2020-11-09 01:37 UTC, MrPointSun commented
确实找不到，大佬我尽力了0.0

2020-12-28 02:32 UTC, zema1 commented
这个可以用 groups 写在一块了

2020-12-30 03:18 UTC, MrPointSun commented
已更新

2020-12-31 03:48 UTC, zema1 commented
很强 感谢大佬

2020-12-31 03:48 UTC, merged