Create showdoc-uploadfile.yml
chaitin/xray pull request #910
Opened 2020-10-15 05:00 UTC by lzskyline

## 本 poc 是检测什么漏洞的

showdoc任意文件上传漏洞(getshell)

## 测试环境

https://fofa.so/result?q=title%3D%22showdoc%22&qbase64=dGl0bGU9InNob3dkb2Mi

## 备注

detail:
author: LzSkyline
links:
- https://github.com/star7th/showdoc/pull/1059
![image](https://user-images.githubusercontent.com/9845170/96079033-5bc77f80-0ee6-11eb-932f-7c8ec2e97640.png)

2020-11-04 07:33 UTC, zema1 requested changes

2020-11-04 07:33 UTC, zema1 commented on pocs/showdoc-uploadfile.yml
> +  - method: GET
期望能实际上传一个文件然后访问一下来证明漏洞存在，单纯这个判断感觉有些弱

2020-11-04 07:33 UTC, zema1 commented on pocs/showdoc-uploadfile.yml
> +        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
不要在 poc 内添加与 poc 无关的头，这个应该在配置文件中写

2021-04-27 07:37 UTC, smile-jpg commented
已合并，#1197，这个就关闭了，感谢提交

2021-04-27 07:37 UTC, closed without merging