add minio-unauthorized-access
chaitin/xray pull request #954
Opened 2020-12-22 06:39 UTC by harris2015

----------

## 本 poc 是检测什么漏洞的
检测minio docker在启动时未加-e参数导致的未授权访问

## 测试环境

网络环境。

## 备注
无

2020-12-22 09:24 UTC, zema1 requested changes

2020-12-22 09:24 UTC, zema1 commented on pocs/minio-unauthorized-access.yml
> +      response.status == 200 && response.body.bcontains(b"uiVersion") && response.body.bcontains(b"token")
这个加个 content-type 的判断吧

2020-12-22 09:24 UTC, zema1 commented on pocs/minio-unauthorized-access.yml
> +name: poc-yaml-minio-unauthorized-access
感觉叫 default-password 更合适

2020-12-22 09:29 UTC, harris2015 commented on pocs/minio-unauthorized-access.yml
> +      response.status == 200 && response.body.bcontains(b"uiVersion") && response.body.bcontains(b"token")
已加

2020-12-22 09:30 UTC, merged

2021-02-05 05:30 UTC, yanyahu commented
method应该是web.Login，目前Web.Login会报错rpc: can't find service \"Web.Login\"

2021-02-05 05:59 UTC, harris2015 commented
> method应该是web.Login，目前Web.Login会报错rpc: can't find service "Web.Login"

大佬方便提供个复现地址吗 我之前测的时候 没看到这个  
联系方式:5oiR55qEcXHvvJo2MTc4NDEzMTY= 多谢

2021-02-05 06:04 UTC, yanyahu commented
@harris2015 参考https://docs.min.io/cn/，直接启动docker，docker run -p 9000:9000 minio/minio server /data

2021-02-05 06:07 UTC, harris2015 commented
> @harris2015 参考https://docs.min.io/cn/ ，直接启动docker，docker run -p 9000:9000 minio/minio server /data

好的 我看下 多谢

2021-02-05 06:14 UTC, yanyahu commented
web.Login和Web.Login两种情况都要考虑，不同版本的要求不一样