poc_CVE-2020-10148
chaitin/xray pull request #967
Opened 2020-12-29 06:51 UTC by suzzz112113

## 本 poc 是检测什么漏洞的
   SolarWinds Orion API存在0Day漏洞，漏洞编号为CVE-2020-10148，该漏洞可允许远程攻击者绕过身份验证，执行未经身份验证的API指令。

## 测试环境
         私聊我。。。。fofa。
## 备注 
影响版本：
   SolarWinds Orion 2020.2.1 HF 2 及 2019.4 HF 6之前的版本

![image](https://user-images.githubusercontent.com/26242452/103264308-4b9f4680-49e5-11eb-9b23-6ad440e15361.png)

2021-01-05 02:31 UTC, zema1 requested changes

2021-01-05 02:31 UTC, zema1 commented on solarwinds-oriona-authentication-bypass.yml
> +name: poc-yaml-solarwinds-oriona-authentication-bypass
有 cve 编号直接用 cve 作为名字吧，比如 solarwinds-cve-xxx

2021-01-06 02:20 UTC, zema1 commented
你提交了两个一样的 poc。。麻烦把另一个去掉吧

2021-01-06 02:29 UTC, suzzz112113 commented
已删除。

2021-01-06 08:25 UTC, zema1 commented
提交的位置不对，应该在 pocs 文件夹

2021-01-06 08:39 UTC, merged

2021-01-06 08:40 UTC, zema1 commented
赞 感谢师傅~