Liferayportal-cve-2020-7961-rce.yml
chaitin/xray pull request #972
Opened 2020-12-31 02:13 UTC by D4ch1au

## 本 poc 是检测什么漏洞的
Liferay Portal代码执行漏洞
## 测试环境
私聊
## 备注

2021-01-05 02:48 UTC, zema1 requested changes

2021-01-05 02:48 UTC, zema1 commented on pocs/liferayportal-cve-2020-7961-rce.yml
> +      cmd2: echo {{r1}}
同样建议改成 expr 的方式

2021-01-05 03:35 UTC, D4ch1au commented on pocs/liferayportal-cve-2020-7961-rce.yml
> +      cmd2: echo {{r1}}
因为这个系统windows和linux上都有部署，所以我用的echo，echo 导致容易误报的问题我暂时也没想到怎么处理

2021-01-06 02:26 UTC, zema1 commented on pocs/liferayportal-cve-2020-7961-rce.yml
> +      cmd2: echo {{r1}}
比较理想的是改下 payload，把输出 echo 到响应头而不是 body 里，这样是很可靠的，xray 的 shiro 检测就是这么做的，https://github.com/zema1/ysoserial/blob/master/src/main/java/ysoserial/payloads/util/Gadgets.java#L213

不过其实这样做也可以接受，10个随机字符已经不容易误报了。如果不想继续做了，可以回复下，我可以合了。

2021-01-07 02:34 UTC, D4ch1au commented on pocs/liferayportal-cve-2020-7961-rce.yml
> +      cmd2: echo {{r1}}
合了吧，感谢大佬。

2021-01-11 03:29 UTC, D4ch1au commented on pocs/liferayportal-cve-2020-7961-rce.yml
> +      cmd=%7B%22%2Fexpandocolumn%2Fadd-column%22%3A%7B%7D%7D&p_auth=nuclei&formDate=1597704739243&tableId=1&name=A&type=1&%2BdefaultData:com.mchange.v2.c3p0.WrapperConnectionPoolDataSource=%7B%22user
不是自己写的，但是公网环境扫不出来应该是漏洞的问题跟poc没关系吧师傅。

2022-12-03 07:27 UTC, closed without merging