Add files via upload
chaitin/xray pull request #991
Opened 2021-01-07 04:31 UTC by Pa55w0rd

**请先认真阅读下列要求，如不符合会被直接关闭 PR**

- 确保当前 POC 与已有的 POC 没有重复，除了仓库 `pocs` 目录中的，还有内置的几个用 Go 写的 POC也不要重复：
  ```
  poc-go-php-cve-2019-11043-rce
  poc-go-seeyon-htmlofficeservlet-rce
  poc-go-tongda-lfi-upload-rce
  poc-go-tongda-arbitrary-auth
  poc-go-ecology-dbconfig-info-leak
  poc-go-tomcat-put
  poc-go-tomcat-cve-2020-1938
  ```
  
- 阅读规范和要求 
  - https://chaitin.github.io/xray/#/guide/contribute
  - https://chaitin.github.io/xray/#/guide/high_quality_poc

- 一个 pull request 只提交一个 poc

- 对于 0day / 1 day 等未大面积公开细节的漏洞请勿提交，可以私聊群管理员

 - 不接受没有测试环境的 poc，测试环境可以使用 [vulhub](https://github.com/vulhub/vulhub/) 或 [vulnapps](https://github.com/Medicean/VulApps)，也可以提供 fofa/zoomeye/shodan 等搜索关键字。 请勿直接填写公网上未修复的站点的地址，如果有特殊情况，请私聊群内管理解决。
 
- 如果你的 poc 被合并或者没有合并但是评论说需要发送奖励，请查看 https://chaitin.github.io/xray/#/guide/feedback 并添加最下面的微信，说明你的 poc 地址，方便发送奖励。

**我是分割线，在提交 poc 填写说明的时候，请务必阅读上方要求，然后删除本分割线和上方的内容，只保留下面自定义的部分即可，否则不予通过。**

----------

## 本 poc 是检测什么漏洞的
src收到好几个/debug/pprof泄露了几个接口，包含了几个未授权的接口
该漏洞存在于Kubelet中，由于用于性能调试的“/debug/pprof“  接口绑跟kubelet的健康检查端口“/healthz”绑定在一起，虽然“/debug/pprof”会进行安全认证，但“/healthz”接口是不认证鉴权的。所以，如果kubelet的healthz地址不是使用localhost，会存在泄露机器敏感信息的风险

## 测试环境
/debug/pprof

## 备注
![image](https://user-images.githubusercontent.com/16274549/103851219-31035680-50e4-11eb-8b43-0ed87ee63344.png)

2021-01-07 07:41 UTC, zema1 requested changes

2021-01-07 07:41 UTC, zema1 commented on pocs/k8s-cve-2019-11248.yml
> +    path: "/debug/pprof/"
这个路径是 go http pprof 的路径，我觉得把它当成 k8s 的洞并不合适。我期望的是两种方式：
1. 把这个漏洞更细化，变成 k8s 这个 cve 的专项检测，k8s 的这个响应是不是有特殊的东西，你写的这两个特征是 go 默认就有的
2. 把 poc 改成 go pprof leak 之类的，同时把规则再细化一下，现在的规则太容易误报了，可以多求请求个链接试试，比如  `debug/pprof/goroutine?debug=2` 这个链接是返回所有的在运行的 goroutine

2021-01-07 10:41 UTC, Pa55w0rd commented on pocs/k8s-cve-2019-11248.yml
> +    path: "/debug/pprof/"
已修改为go-pprof-leak，请求了debug/pprof/goroutine?debug=1 ，参考https://cloud.tencent.com/developer/news/312276，/debug/pprof/goroutine?debug=1: 所有协程的堆栈踪迹，应该就减少很多误报

2021-01-14 09:33 UTC, merged

2021-01-14 09:33 UTC, zema1 commented
感谢大佬提交~